#ifndef MODE_HELPER_H
#define MODE_HELPER_H

#define MODE_SCALE_FULL 0b11
#define MODE_SCALE_HALF 0b10
#define MODE_SCALE_QUARTER 0b01

#define MODE_OVERLAY_NONE 0b00
#define MODE_OVERLAY_CHROMA_KEY 0b01
#define MODE_OVERLAY_DIRECT 0b10

#endif